name: Deploy Hugo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: Deploy via Rclone
        uses: 7H3LaughingMan/actions-rclone@main
        with:
          entrypoint: 'ls -la'
          #args: copy publish webdav:/
        env:
          RCLONE_CONFIG_WEBDAV_TYPE: webdav
          RCLONE_CONFIG_WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          RCLONE_CONFIG_WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          RCLONE_CONFIG_WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
