name: Deploy Hugo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify
        
      - name: Upload to WebDAV
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_URL }}
            username=${{ secrets.WEBDAV_USER }}
            password=${{ secrets.WEBDAV_PASS }}
            root=/test/
          include: 'publish/**'
